ipc:
	gcc ipa.c -o ipa
	gcc ipb.c -o ipb
sock:
	gcc socketa.c -o sa
	gcc socketb.c -o sb
msg:
	gcc quene.c -o quene
	gcc quene1.c -o quene1
shm:
	gcc  sharedmem.c -o sharedmem
	gcc getmem.c -o getmem
