######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 11 21:31:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_1.cpp
